// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/crud.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PrivateUserInfo struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivateUserInfo) Reset()         { *m = PrivateUserInfo{} }
func (m *PrivateUserInfo) String() string { return proto.CompactTextString(m) }
func (*PrivateUserInfo) ProtoMessage()    {}
func (*PrivateUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_06787495a7c0d2a8, []int{0}
}

func (m *PrivateUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivateUserInfo.Unmarshal(m, b)
}
func (m *PrivateUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivateUserInfo.Marshal(b, m, deterministic)
}
func (m *PrivateUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivateUserInfo.Merge(m, src)
}
func (m *PrivateUserInfo) XXX_Size() int {
	return xxx_messageInfo_PrivateUserInfo.Size(m)
}
func (m *PrivateUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivateUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PrivateUserInfo proto.InternalMessageInfo

func (m *PrivateUserInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *PrivateUserInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserInfo struct {
	Info                 *PrivateUserInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Firstname            string           `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string           `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_06787495a7c0d2a8, []int{1}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetInfo() *PrivateUserInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *UserInfo) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *UserInfo) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func init() {
	proto.RegisterType((*PrivateUserInfo)(nil), "PrivateUserInfo")
	proto.RegisterType((*UserInfo)(nil), "UserInfo")
}

func init() { proto.RegisterFile("proto/crud.proto", fileDescriptor_06787495a7c0d2a8) }

var fileDescriptor_06787495a7c0d2a8 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x2e, 0x2a, 0x4d, 0xd1, 0x03, 0x33, 0x95, 0x3c, 0xb9, 0xf8, 0x03, 0x8a, 0x32,
	0xcb, 0x12, 0x4b, 0x52, 0x43, 0x8b, 0x53, 0x8b, 0x3c, 0xf3, 0xd2, 0xf2, 0x85, 0xa4, 0xb8, 0x38,
	0x4a, 0x8b, 0x53, 0x8b, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xe0,
	0x7c, 0x90, 0x5c, 0x41, 0x62, 0x71, 0x71, 0x79, 0x7e, 0x51, 0x8a, 0x04, 0x13, 0x44, 0x0e, 0xc6,
	0x57, 0xca, 0xe2, 0xe2, 0x80, 0x9b, 0xa1, 0xc2, 0xc5, 0x92, 0x99, 0x97, 0x96, 0x0f, 0xd6, 0xcf,
	0x6d, 0x24, 0xa0, 0x87, 0x66, 0x47, 0x10, 0x58, 0x56, 0x48, 0x86, 0x8b, 0x33, 0x2d, 0xb3, 0xa8,
	0xb8, 0x04, 0x6c, 0x15, 0xc4, 0x38, 0x84, 0x00, 0xc8, 0xae, 0x9c, 0x44, 0xa8, 0x24, 0x33, 0xc4,
	0x2e, 0x18, 0xdf, 0x68, 0x26, 0x23, 0x17, 0x0b, 0xc8, 0x17, 0x42, 0x0a, 0x5c, 0x6c, 0xce, 0x45,
	0xa9, 0x89, 0x25, 0xa9, 0x42, 0x9c, 0x7a, 0x30, 0xd3, 0xa5, 0x10, 0x4c, 0x25, 0x06, 0x21, 0x15,
	0x2e, 0x66, 0xf7, 0xd4, 0x12, 0x21, 0x0c, 0x37, 0xa0, 0xaa, 0x52, 0xe0, 0x62, 0x0b, 0x2d, 0x48,
	0xc1, 0x67, 0x8e, 0x3a, 0x17, 0x9b, 0x4b, 0x6a, 0x4e, 0x6a, 0x49, 0x2a, 0x01, 0xa3, 0x9c, 0x38,
	0xa2, 0xd8, 0xf4, 0xc1, 0x81, 0x9b, 0xc4, 0x06, 0xa6, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x03, 0x64, 0x8b, 0x59, 0x77, 0x01, 0x00, 0x00,
}
